По какой причине не завершается работа функции main? Ответ очень прост. При выполнении кода происходит взаимная блокировка.Взаимная блокировка возникает, когда два или более потока блокируют ресурсы, которые другие потоки пытаются заблокировать в обратной последовательности, и, таким образом, они блокируют друг друга и не могут продолжить выполнение.
В вашем коде два потока t1 и t2 запускаются параллельно и пытаются захватить два ресурса resourceA и resourceB в разных последовательностях. Поскольку t1 пытается сначала захватить resourceA, а затем resourceB, а t2 делает наоборот, сначала захватывая resourceB, а затем resourceA, есть вероятность, что они заблокируют друг друга и не смогут завершить выполнение.

Для избежания deadlock нужно обеспечить одинаковый порядок захвата ресурсов в обоих потоках. Например, изменить порядок блокировки в одном из потоков следующим образом:
val t1 = thread {
consumerA.lockFirstAndTrySecond(resourceA, resourceB)
}
val t2 = thread {
consumerB.lockFirstAndTrySecond(resourceA, resourceB)
}
